services:
  - type: web
    name: movie-bot
    runtime: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL
        sync: false
